/*
 * This Java source file was generated by the jvm-library 'init' task.
 */
package com.qubole.sparklens;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class InitLibraryTest {
    @Test void someInitLibraryMethodReturnsTrue() {
        InitLibrary classUnderTest = new InitLibrary();
        assertTrue(classUnderTest.someInitLibraryMethod(), "someInitLibraryMethod should return 'true'");
    }
}
