/*
 * This Java source file was generated by the jvm-library 'init' task.
 */
package com.qubole.sparklens;

public class InitLibrary {
    public boolean someInitLibraryMethod() {
        return true;
    }
}
