name: Build and test

on:
  push:
    branches:
    - '**'
    - '!branch-*.*'

jobs:
  # Build: build spark-testing-base and run the tests for specified modules.
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        spark:
          - 3.3.4
          - 3.4.1
          - 3.5.1
    env:
      SPARK_VERSION: ${{ matrix.spark }}
    steps:
    - name: Checkout spark-testing-base
      uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Run tests
      run: SPARK_TESTING=yes sbt clean +compile +test -DsparkVersion=$SPARK_VERSION
